FLASK_SERVER_NAME = 'localhost:8000'
FLASK_DEBUG = True

APP_API_CONTEXT = 'stock_api'
REGISTRY_APP_CONTEXT = '/stock_api'
FLASK_APP_CONTEXT = '/stock_api'

APP_NAME = 'stock_api'

RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False
